import { motion, AnimatePresence } from "framer-motion";
import PackageCard from "@/components/packages/package-card";
import { PackageType } from "@/types";

const packages: PackageType[] = [
  // Budget Friendly Packages
  {
    id: "angkor-wonder",
    title: "Angkor Wonder",
    description: "4 days exploring ancient temples with expert guides",
    price: 1899,
    duration: "4 Days / 3 Nights",
    rating: 4.8,
    reviews: 156,
    category: ["cultural", "budget"],
    image: "https://images.unsplash.com/photo-1584607889131-98d098f01f60?q=80&w=943&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Budget Friendly",
    badgeColor: "blue",
    includes: [
      "Private temple tours",
      "Sunrise Angkor Wat visit",
      "Traditional Khmer cooking class",
      "Cultural performances",
      "Professional photographer",
    ],
  },
  {
    id: "swiss-alps-trek",
    title: "Swiss Alps Adventure",
    description: "5 days hiking with luxury mountain lodges",
    price: 2799,
    duration: "5 Days / 4 Nights",
    rating: 4.7,
    reviews: 89,
    category: ["adventure", "budget"],
    image: "https://images.unsplash.com/photo-1517079495967-03aed29f98b5?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Budget Friendly",
    badgeColor: "blue",
    includes: [
      "Professional mountain guide",
      "All hiking equipment",
      "Gourmet mountain meals",
      "Cable car passes",
      "Photography workshop",
    ],
  },
  {
    id: "kenya-safari",
    title: "Kenya Wildlife Safari",
    description: "6 days exploring Masai Mara with expert guides",
    price: 3499,
    duration: "6 Days / 5 Nights",
    rating: 4.6,
    reviews: 203,
    category: ["adventure", "budget"],
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Budget Friendly",
    badgeColor: "blue",
    includes: [
      "Game drives twice daily",
      "Professional wildlife guide",
      "All meals included",
      "Cultural village visit",
      "Hot air balloon safari",
    ],
  },
  {
    id: "patagonia-trek",
    title: "Patagonia Expedition",
    description: "7 days exploring Torres del Paine with eco lodges",
    price: 4299,
    duration: "7 Days / 6 Nights",
    rating: 4.8,
    reviews: 134,
    category: ["adventure", "budget"],
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Budget Friendly",
    badgeColor: "blue",
    includes: [
      "Expert trekking guide",
      "All camping equipment",
      "Glacier boat tour",
      "Wildlife spotting",
      "Photography workshop",
    ],
  },

  // Ultra Luxury Packages
  {
    id: "maldives-paradise",
    title: "Maldives Ocean Villa",
    description: "7 nights in overwater villa with private butler service",
    price: 8999,
    duration: "7 Days / 6 Nights",
    rating: 4.9,
    reviews: 127,
    category: ["luxury"],
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Ultra Luxury",
    badgeColor: "gold",
    includes: [
      "Seaplane transfers",
      "All meals and premium beverages",
      "Spa treatments",
      "Private island excursions",
      "Sunset dolphin cruise",
    ],
  },
  {
    id: "antarctica-expedition",
    title: "Antarctica Luxury Expedition",
    description: "12 days aboard luxury icebreaker with expert naturalists",
    price: 28999,
    duration: "12 Days / 11 Nights",
    rating: 5.0,
    reviews: 45,
    category: ["luxury", "adventure"],
    image: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Ultra Luxury",
    badgeColor: "gold",
    includes: [
      "Luxury icebreaker cabin",
      "Expert naturalist guides",
      "Zodiac wildlife tours",
      "Photography workshops",
      "Champagne ice tasting",
    ],
  },
  {
    id: "dubai-penthouse",
    title: "Dubai Penthouse Suite",
    description: "5 nights in Burj Al Arab Royal Suite with helicopter transfers",
    price: 22999,
    duration: "5 Days / 4 Nights",
    rating: 5.0,
    reviews: 67,
    category: ["luxury"],
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Ultra Luxury",
    badgeColor: "gold",
    includes: [
      "Burj Al Arab Royal Suite",
      "Helicopter transfers",
      "Private desert safari",
      "Yacht charter",
      "Personal shopping stylist",
    ],
  },
  {
    id: "iceland-northern-lights",
    title: "Iceland Glass Igloo Experience",
    description: "5 nights in glass igloos with aurora hunting tours",
    price: 6299,
    duration: "5 Days / 4 Nights",
    rating: 4.9,
    reviews: 198,
    category: ["luxury", "adventure"],
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Ultra Luxury",
    badgeColor: "gold",
    includes: [
      "Glass igloo accommodation",
      "Aurora hunting tours",
      "Blue Lagoon spa access",
      "Glacier hiking",
      "Reykjavik city tours",
    ],
  },

  // Wine Master Packages
  {
    id: "tuscany-wine-estate",
    title: "Tuscany Wine Estate",
    description: "14 nights in private vineyard with wine master",
    price: 15999,
    duration: "14 Days / 13 Nights",
    rating: 4.9,
    reviews: 156,
    category: ["luxury", "cultural"],
    image: "https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Wine Master",
    badgeColor: "purple",
    includes: [
      "Private estate residence",
      "Personal sommelier",
      "Cooking classes with Michelin chef",
      "Ferrari countryside tours",
      "Exclusive vineyard access",
    ],
  },
  {
    id: "bordeaux-wine-tour",
    title: "Bordeaux Grand Cru Tour",
    description: "10 nights exploring prestigious châteaux with wine experts",
    price: 12999,
    duration: "10 Days / 9 Nights",
    rating: 4.8,
    reviews: 112,
    category: ["luxury", "cultural"],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Wine Master",
    badgeColor: "purple",
    includes: [
      "Château luxury suites",
      "Private cellar tours",
      "Wine tasting with masters",
      "French cooking classes",
      "Luxury river cruise",
    ],
  },
  {
    id: "champagne-region",
    title: "Champagne Region Exclusive",
    description: "8 nights in historic champagne houses with master tastings",
    price: 9999,
    duration: "8 Days / 7 Nights",
    rating: 4.9,
    reviews: 89,
    category: ["luxury", "cultural"],
    image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Wine Master",
    badgeColor: "purple",
    includes: [
      "Historic champagne house stay",
      "Master champagne tastings",
      "Underground cellar tours",
      "Gourmet dining experiences",
      "Hot air balloon over vineyards",
    ],
  },
  {
    id: "napa-valley-luxury",
    title: "Napa Valley Luxury Estate",
    description: "7 nights in private winery estate with harvest experiences",
    price: 8999,
    duration: "7 Days / 6 Nights",
    rating: 4.7,
    reviews: 145,
    category: ["luxury", "cultural"],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Wine Master",
    badgeColor: "purple",
    includes: [
      "Private winery estate",
      "Harvest participation",
      "Wine blending workshop",
      "Michelin star dining",
      "Helicopter vineyard tours",
    ],
  },

  // Cultural Immersion Packages
  {
    id: "japan-private-ryokan",
    title: "Japan Private Ryokan Experience",
    description: "8 nights in exclusive traditional inn with kaiseki dining",
    price: 11299,
    duration: "8 Days / 7 Nights",
    rating: 5.0,
    reviews: 74,
    category: ["luxury", "cultural"],
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Cultural Immersion",
    badgeColor: "red",
    includes: [
      "Private ryokan with hot springs",
      "Daily kaiseki meals",
      "Tea ceremony master",
      "Private temple meditation",
      "Mount Fuji helicopter tour",
    ],
  },
  {
    id: "bhutan-monastery",
    title: "Bhutan Monastery Retreat",
    description: "10 nights in sacred monasteries with meditation masters",
    price: 7999,
    duration: "10 Days / 9 Nights",
    rating: 4.9,
    reviews: 56,
    category: ["cultural", "adventure"],
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Cultural Immersion",
    badgeColor: "red",
    includes: [
      "Monastery accommodation",
      "Daily meditation sessions",
      "Himalayan trekking",
      "Traditional cooking classes",
      "Tiger's Nest monastery visit",
    ],
  },
  {
    id: "morocco-imperial",
    title: "Morocco Imperial Cities",
    description: "12 nights exploring royal palaces with cultural experts",
    price: 6999,
    duration: "12 Days / 11 Nights",
    rating: 4.6,
    reviews: 178,
    category: ["cultural", "luxury"],
    image: "https://images.unsplash.com/photo-1539650116574-75c0c6d73dc0?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Cultural Immersion",
    badgeColor: "red",
    includes: [
      "Royal palace accommodations",
      "Expert cultural guides",
      "Traditional hammam experiences",
      "Berber desert camping",
      "Artisan workshop visits",
    ],
  },
  {
    id: "peru-inca-trail",
    title: "Peru Sacred Valley Journey",
    description: "9 nights exploring Inca heritage with archaeological experts",
    price: 5999,
    duration: "9 Days / 8 Nights",
    rating: 4.8,
    reviews: 234,
    category: ["cultural", "adventure"],
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Cultural Immersion",
    badgeColor: "red",
    includes: [
      "Archaeological expert guides",
      "Luxury Sacred Valley lodges",
      "Private Machu Picchu access",
      "Traditional weaving workshops",
      "Shamanic ceremonies",
    ],
  },

  // Private Suite Packages
  {
    id: "bali-private-villa",
    title: "Bali Clifftop Villa Sanctuary",
    description: "10 nights in exclusive clifftop villa with infinity pool",
    price: 12499,
    duration: "10 Days / 9 Nights",
    rating: 5.0,
    reviews: 89,
    category: ["luxury", "private"],
    image: "https://images.unsplash.com/photo-1537953773345-d172ccf13cf1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Private Suite",
    badgeColor: "emerald",
    includes: [
      "Private jet transfers",
      "24/7 personal chef",
      "Daily spa treatments",
      "Private temple tours",
      "Helicopter island hopping",
    ],
  },
  {
    id: "seychelles-private-island",
    title: "Seychelles Private Island",
    description: "14 nights on exclusive private island with full staff",
    price: 35999,
    duration: "14 Days / 13 Nights",
    rating: 5.0,
    reviews: 23,
    category: ["luxury", "private"],
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Private Suite",
    badgeColor: "emerald",
    includes: [
      "Entire private island",
      "Full domestic staff",
      "Private yacht charter",
      "Helicopter transfers",
      "World-class diving guide",
    ],
  },
  {
    id: "norwegian-fjords",
    title: "Norway Private Yacht Charter",
    description: "11 nights aboard luxury yacht exploring dramatic fjords",
    price: 18999,
    duration: "11 Days / 10 Nights",
    rating: 4.9,
    reviews: 67,
    category: ["luxury", "private", "adventure"],
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Private Suite",
    badgeColor: "emerald",
    includes: [
      "Private luxury yacht",
      "Professional crew",
      "Gourmet Nordic cuisine",
      "Zodiac expedition boat",
      "Northern lights viewing deck",
    ],
  },
  {
    id: "swiss-alpine-chalet",
    title: "Swiss Alpine Private Chalet",
    description: "9 nights in exclusive mountain chalet with ski concierge",
    price: 16999,
    duration: "9 Days / 8 Nights",
    rating: 4.8,
    reviews: 134,
    category: ["luxury", "private", "adventure"],
    image: "https://images.unsplash.com/photo-1551524164-6cf4ac833fb6?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80",
    badge: "Private Suite",
    badgeColor: "emerald",
    includes: [
      "Private alpine chalet",
      "Personal ski instructor",
      "Helicopter skiing access",
      "Private chef service",
      "Spa and wellness center",
    ],
  },
];
      "Game drives in Masai Mara",
      "Cultural village visit",
      "Hot air balloon safari",
      "Bush breakfast experience",
    ],
  },
  {
    id: "japan-culture",
    title: "Japan Culture",
    description: "8 days immersive cultural experience with ryokan stays",
    price: 4299,
    duration: "8 Days / 7 Nights",
    rating: 4.8,
    reviews: 95,
    category: ["cultural", "luxury"],
    image: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Cultural",
    badgeColor: "pink",
    includes: [
      "Traditional ryokan stays",
      "Tea ceremony workshops",
      "Private temple visits",
      "Kaiseki dining experiences",
      "Geisha district tours",
    ],
  },
  {
    id: "iceland-northern-lights",
    title: "Iceland Northern Lights",
    description: "5 days aurora hunting with luxury glacier lodge",
    price: 6299,
    duration: "5 Days / 4 Nights",
    rating: 4.7,
    reviews: 128,
    category: ["adventure", "luxury"],
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Northern Lights",
    badgeColor: "purple",
    includes: [
      "Glass igloo accommodation",
      "Aurora hunting tours",
      "Blue Lagoon spa access",
      "Glacier hiking expedition",
      "Reykjavik city tour",
    ],
  },
  {
    id: "bali-private-villa",
    title: "Bali Private Villa Retreat",
    description: "7 days in exclusive cliff-side villa with personal chef",
    price: 8599,
    duration: "7 Days / 6 Nights",
    rating: 4.9,
    reviews: 89,
    category: ["luxury", "private"],
    image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1200&q=80",
    badge: "Private Villa",
    badgeColor: "green",
    includes: [
      "Private cliff-side villa",
      "Personal chef and butler",
      "Helicopter temple tours",
      "Traditional spa treatments",
      "Sunset yacht charter",
    ],
  },
  {
    id: "norway-fjords",
    title: "Norway Fjords Explorer",
    description: "9 days scenic railway and fjord cruise combination",
    price: 9299,
    duration: "9 Days / 8 Nights",
    rating: 4.7,
    reviews: 134,
    category: ["adventure", "luxury"],
    image: "https://plus.unsplash.com/premium_photo-1668017178979-9e341bfaa464?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Fjord Explorer",
    badgeColor: "blue",
    includes: [
      "Premium fjord cruise",
      "Scenic railway journeys",
      "Northern lights hunting",
      "Gourmet Nordic cuisine",
      "Cultural performances",
    ],
  },
];

interface PackageGridProps {
  activeFilter: string;
}

export default function PackageGrid({ activeFilter }: PackageGridProps) {
  const filteredPackages = packages.filter((pkg) => {
    if (activeFilter === "all") return true;
    return pkg.category.includes(activeFilter);
  });

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, scale: 0.8 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: { duration: 0.4, ease: "easeOut" },
    },
  };

  return (
    <motion.div
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="grid md:grid-cols-2 lg:grid-cols-3 gap-8"
    >
      <AnimatePresence>
        {filteredPackages.map((pkg) => (
          <motion.div
            key={pkg.id}
            variants={itemVariants}
            layout
            initial="hidden"
            animate="visible"
            exit="hidden"
          >
            <PackageCard package={pkg} />
          </motion.div>
        ))}
      </AnimatePresence>
    </motion.div>
  );
}
